kind: pipeline
type: docker
name: firefly update

steps:
- name: configure mail
  image: alpine
  settings:
    fromaddress:
      from_secret: ORG_MAIL_FROM_ADDRESS
    fromname:
      from_secret: ORG_MAIL_FROM_NAME
    host: 
      from_secret: ORG_MAIL_SMTP_SERVER
    recipients_only: true
    recipients:
      from_secret: ORG_MAIL_RECIPIENTS
    username:
      from_secret: ORG_MAIL_SMTP_USERNAME
    password:
      from_secret: ORG_MAIL_SMTP_PASSWORD
    fireflyurl:
      from_secret: FIREFLY_URL
    fireflytoken:
      from_secret: FIREFLY_TOKEN
  commands:
  - "echo -e \"---\nsmtp:\n  server: $PLUGIN_HOST\n  port: 587\n  starttls: True\n  authentication: True\n  user: $PLUGIN_USERNAME\n  password: $PLUGIN_PASSWORD\nemail:\n  from: $PLUGIN_FROMADDRESS\n  to:\n    - $PLUGIN_RECIPIENTS\nfirefly-url: '$PLUGIN_FIREFLYURL'\naccesstoken: '$PLUGIN_FIREFLYTOKEN'\ncurrency: 'EUR'\" > config.yaml"
- name: send mail
  image: python
  commands:
  - cat config.yaml
  - pip install -r requirements.txt
  - python monthly-report.py
  ports:
  - 587
  depends_on:
  - configure mail

trigger:
  event:
    include:
    - promote
    - custom
    - cron
